### ISSUE TITLE
I cant run at 1.20.1 Minecraft Version

### ISSUE THREAD

**Issue by SaintSaka** [Ramixin/SlashLength#1]
1.20.1 uses JAVA 17, not JAVA 21

**Comment by Ramixin** [comment]
Although 1.20.1 was built using JAVA 21, JAVA is backward compatible, which means anything written in JAVA 17 will work with JAVA 21. Since Minecraft 1.20.5+ requires JAVA 21, the entire mod needs to be that version. You can install JAVA 21 here and never have this issue again (until the next official java release): https://adoptium.net/temurin/releases/
